version: "3.8"

services:
  backend:
    image: backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    healthcheck:
      test: [ "CMD", "ping" ,"localhost:8000" ]
      timeout: 20s
      retries: 10
    links:
      - mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy

  frontend:
    image: frontend
    ports:
      - 8080:8080
    depends_on:
      backend:
        condition: service_healthy

  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    environment:
      MYSQL_DATABASE: 'djangoDB'
      MYSQL_ROOT_PASSWORD: 'passwd'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'mysqlpasswd'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql:
  mysql_config:
